######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 15 09:28:30 2014
######################################################################

DEPENDPATH += .
INCLUDEPATH += .

CONFIG  += c++11
QT      += testlib
QT      -= gui

HEADERS += \
    ../src/bigint.hpp

SOURCES += \
    ../src/bigint.cpp \
    #test_bigint.cpp \
    ../src/mycode.cpp \
    test_mycode.cpp
