######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 15 09:28:30 2014
######################################################################

DEPENDPATH += .
INCLUDEPATH += .

CONFIG  += c++11
QT      += testlib
QT      -= gui
QT += core gui testlib widgets # Убедитесь, что 'widgets' присутствует, если используется QWidget


HEADERS += \
    ../src/form.h

SOURCES += \
    ../src/form.cpp \
    test_mycode.cpp

FORMS += \
    ../src/form.ui
